### ISSUE TITLE
AttributeError: 'EdgeStorage' object has no attribute 'edge_label_index'

### ISSUE THREAD

**Issue by quail768** [EliHei2/segger_dev#34]
---
name: Bug Report
about: Report a bug or unexpected behavior
title: "[BUG] `"`
labels: bug
assignees: ''

---

**Describe the bug**
Segmentation stalls  with  AttributeError: 'EdgeStorage' object has no attribute 'edge_label_index'

**To Reproduce**
```
Steps to reproduce the behavior:
from segger.data.io import XeniumSample
from segger.training.train import LitSegger
from segger.training.segger_data_module import SeggerDataModule
from segger.prediction.predict import predict, load_model, segment
from lightning.pytorch.loggers import CSVLogger
from pytorch_lightning import Trainer
from pathlib import Path
from lightning.pytorch.plugins.environments import LightningEnvironment
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

#Segger_data
xenium_data_dir = Path('/mnt/N5_T1')
segger_data_dir = Path('/mnt/segger_D/')
models_dir = Path('/mnt/models')

# Checkpoint directory for Lightning model above
model_version = 0

# Load in latest checkpoint
model_path = models_dir / 'lightning_logs' / f'version_{model_version}'
model = load_model(model_path / 'checkpoints')
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=2,  
    num_workers=5,  
)

dm.setup()

# Define the required parameters
save_directory = Path('/mnt/Save')
segmentation_tag = 'N5_T1'  
transcript_file_path = Path('/mnt/N5_T1/transcripts.parquet')  
score_cutoff = 0.5  
# Optional parameters
file_format = 'anndata'  
use_connected_components = False 
knn_algorithm = 'kd_tree' 
verbose_output = True  

# Receptive field configuration
receptive_field_config = {'k_bd': 4, 'dist_bd': 12, 'k_tx': 15, 'dist_tx': 3}

# Call the `segment` function
segment(
    model=model, 
    dm=dm, 
    save_dir=save_directory, 
    seg_tag=segmentation_tag, 
    transcript_file=transcript_file_path, 
    score_cut=score_cutoff, 
    use_cc=use_connected_components, 
    file_format=file_format, 
    receptive_field=receptive_field_config, 
    knn_method=knn_algorithm, 
    verbose=verbose_output
)
```
**Expected behavior**
Segmentation completes to the end

**Screenshots or logs**
```
Traceback (most recent call last):
  File "/Segger/Segment.py", line 56, in <module>
    segment(
  File "/segger_dev/src/segger/prediction/predict.py", line 406, in segment
    segmentation_test  = predict(model, test_dataloader, score_cut, receptive_field, use_cc, knn_method)
  File "/segger_dev/src/segger/prediction/predict.py", line 296, in predict
    for batch in data_loader:
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 291, in __getitem__
    data = self.get(self.indices()[idx])
  File "/segger_dev/src/segger/data/parquet/pyg_dataset.py", line 71, in get
    if data['tx', 'belongs', 'bd'].edge_label_index.dim() == 1:
  File "/opt/conda/envs/segger/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 96, in __getattr__
    raise AttributeError(
AttributeError: 'EdgeStorage' object has no attribute 'edge_label_index'
```

**Environment (please complete the following information):**
- OS: Ubuntu 22.04
- Python version: 3.10
- Package version: 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
adjusttext                1.2.0                    pypi_0    pypi
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anndata                   0.10.9                   pypi_0    pypi
array-api-compat          1.9                      pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
bounded-pool-executor     0.0.3                    pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.1.0                    pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cuda-python               12.6.0                   pypi_0    pypi
cupy-cuda12x              13.3.0                   pypi_0    pypi
cuvs-cu12                 24.4.0                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.9.0                 pypi_0    pypi
dask-cuda                 24.10.0                  pypi_0    pypi
dask-expr                 1.1.14                   pypi_0    pypi
dask-geopandas            0.4.2                    pypi_0    pypi
dask-image                2024.5.3                 pypi_0    pypi
distributed               2024.9.0                 pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
faiss-cpu                 1.9.0                    pypi_0    pypi
faiss-gpu                 1.7.2                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
fastrlock                 0.8.2                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.9.0                 pypi_0    pypi
geopandas                 1.0.1                    pypi_0    pypi
h5py                      3.12.1                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
igraph                    0.11.6                   pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
inflect                   7.4.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
legacy-api-wrap           1.4                      pypi_0    pypi
leidenalg                 0.10.2                   pypi_0    pypi
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lightning                 2.4.0                    pypi_0    pypi
lightning-utilities       0.11.7                   pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                3.0.1                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-scalebar       0.8.1                    pypi_0    pypi
more-itertools            10.5.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
networkx                  3.4.1                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numcodecs                 0.13.1                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
omnipath                  1.0.8                    pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
partd                     1.4.2                    pypi_0    pypi
path                      17.0.0                   pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pims                      0.7                      pypi_0    pypi
pip                       24.2               pyh8b19718_1    conda-forge
pqdm                      0.2.0                    pypi_0    pypi
propcache                 0.2.0                    pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pyarrow                   16.1.0                   pypi_0    pypi
pylibraft-cu12            24.4.0                   pypi_0    pypi
pynndescent               0.5.13                   pypi_0    pypi
pynvml                    11.4.1                   pypi_0    pypi
pyogrio                   0.10.0                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyproj                    3.7.0                    pypi_0    pypi
python                    3.10.15         h4a871b0_1_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         2.4.0                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
rapids-dask-dependency    24.10.0                  pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3                   pypi_0    pypi
rmm-cu12                  24.4.0                   pypi_0    pypi
scanpy                    1.10.3                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
segger                    0.1.0                    pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
slicerator                1.1.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
squidpy                   1.2.0                    pypi_0    pypi
statsmodels               0.14.4                   pypi_0    pypi
stdlib-list               0.10.0                   pypi_0    pypi
sympy                     1.13.3                   pypi_0    pypi
tblib                     3.0.0                    pypi_0    pypi
texttable                 1.7.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.9.20                pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     1.0.0                    pypi_0    pypi
torch                     2.4.1                    pypi_0    pypi
torch-geometric           2.6.1                    pypi_0    pypi
torchmetrics              1.4.3                    pypi_0    pypi
torchvision               0.19.1                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typeguard                 4.3.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
umap-learn                0.5.6                    pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
validators                0.34.0                   pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0                   pypi_0    pypi
xarray                    2024.9.0                 pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.15.0                   pypi_0    pypi
zarr                      2.18.3                   pypi_0    pypi
zict                      3.0.0                    pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi

**Additional context**

**Comment by EliHei2** [comment]
@quail768 could you try the datamodule with these parameters?

```
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=1,  
    num_workers=1,  
)
```

**Comment by quail768** [comment]
Hey @EliHei2, Unfortunately it still does not work.  Maybe unrelated, but I tried rerunning the predict function after pulling the latest version and it is much slower than before although the job hasn't crashed yet.

**Comment by EliHei2** [comment]
@quail768 thanks for reporting.  is `predict` slower or `segment`?

**Comment by quail768** [comment]
Segment does not run because of the AttributeError: 'EdgeStorage' object has no attribute 'edge_label_index' . Predict is much slower.
 I also tried to train the model again with the updated version and the training is going really badly on the same data.
This is the original model, from a version pulled 3 weeks ish ago:
![image](https://github.com/user-attachments/assets/41a1a46f-6b39-4a0e-9eca-4b6d5ab7f915)
This is the model trained using the version pulled today:
![image](https://github.com/user-attachments/assets/8c21baf8-3980-4f0f-a395-25e93eaab263)

Run on parameters from the tutorial:
```
# Initialize the Lightning model
metadata = (["tx", "bd"], [("tx", "belongs", "bd"), ("tx", "neighbors", "tx")])
ls = LitSegger(
    num_tx_tokens=500,
    init_emb=15,
    hidden_channels=32,
    out_channels=15,
    heads=3,
    num_mid_layers=7,
    aggr='sum',
    metadata=metadata,
)

# Initialize the Lightning data module
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=2,  
    num_workers=6,  
)

dm.setup()


# if you wish to use more than 1 device for training you should run this:
batch = dm.train[0]
ls.forward(batch)

# Initialize the Lightning trainer
trainer = Trainer(
    accelerator='cuda',  
    strategy='auto',
    precision='16-mixed',
    devices=2,  
    max_epochs=100,  
    default_root_dir=models_dir,
    logger=CSVLogger(models_dir),
)

# Fit model
trainer.fit(
    model=ls,
    datamodule=dm
)
```

**Comment by EliHei2** [comment]
> Predict is much slower and hasn't yet finished after 7ish hours
do you run predict with `use_cc=True`? If so, that's expected, we're gonna make a new PR soon that makes it way faster. if you're running with `use_cc=False` that's odd, maybe the code is stuck somewhere. 


> I also tried to train the model again with the updated version and the training is going really badly on the same data.
we have not really changed the model (re training), is this effect reproducible? could you get another run and approve?

> I did not pre-process and tile that parquet file again with the new version, would that be the source of the issue you think?
I think we made everything compatible in the new changes, so shouldn't be an issue, but @andrewmoorman what do you think?

**Comment by EliHei2** [comment]
@daniel-unyi-42 could you please look into this?

> Segment terminates after 50 minutes because of the AttributeError: 'EdgeStorage' object has no attribute 'edge_label_index' . Predict is much slower and hasn't yet finished after 7ish hours

**Comment by daniel-unyi-42** [comment]
Fixed [here](https://github.com/EliHei2/segger_dev/pull/42/commits/589fafe046e554480e4f3d1c7b09f19fffb1b511)

**Comment by quail768** [comment]
Hello
The fixes work now, thanks!

The model training with the parameters from the tutorial still is pretty bad on my data. I tuned some parameters and I think it's okay for a first try:
![image](https://github.com/user-attachments/assets/bd0af85e-6905-4a8f-b798-5e0a97d56ec6)

The prediction and segmentation issues were fixed by Daniel's change:
![image](https://github.com/user-attachments/assets/a5dc3101-657a-420a-8b10-1c9b35361a13)
 and now i have my segmented file!

**Comment by quail768** [comment]
Hey @daniel-unyi-42. Sorry to bother you again but the error is back in the new build.

```
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "segger/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "segger/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "segger/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "segger/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 291, in __getitem__
    data = self.get(self.indices()[idx])
  File "/segger_dev/src/segger/data/parquet/pyg_dataset.py", line 71, in get
    if data['tx', 'belongs', 'bd'].edge_label_index.dim() == 1:
  File "segger/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 96, in __getattr__
    raise AttributeError(
AttributeError: 'EdgeStorage' object has no attribute 'edge_label_index'

```

**Comment by daniel-unyi-42** [comment]
@EliHei2 this must be an older version

[Line 71](https://github.com/EliHei2/segger_dev/blob/main/src/segger/data/parquet/pyg_dataset.py#L71) is different now

**Comment by quail768** [comment]
This is the entire file. I cloned the repo and installed today:
```
from typing import List, Optional, Callable
from torch_geometric.data import InMemoryDataset, Data
import glob
import os
from pathlib import Path
import torch


class STPyGDataset(InMemoryDataset):
    """
    An in-memory dataset class for handling training using spatial
    transcriptomics data.
    """

    def __init__(
        self,
        root: str,
        transform: Optional[Callable] = None,
        pre_transform: Optional[Callable] = None,
        pre_filter: Optional[Callable] = None,
    ):
        super().__init__(root, transform, pre_transform, pre_filter)

    @property
    def raw_file_names(self) -> List[str]:
        """
        Return a list of raw file names in the raw directory.

        Returns:
            List[str]: List of raw file names.
        """
        return os.listdir(self.raw_dir)

    @property
    def processed_file_names(self) -> List[str]:
        """
        Return a list of processed file names in the processed directory.

        Returns:
            List[str]: List of processed file names.
        """
        paths = glob.glob(f"{self.processed_dir}/tiles_x*_y*_*_*.pt")
        # paths = paths.append(paths = glob.glob(f'{self.processed_dir}/tiles_x*_y*_*_*.pt'))
        file_names = list(map(os.path.basename, paths))
        return file_names

    def len(self) -> int:
        """
        Return the number of processed files.

        Returns:
            int: Number of processed files.
        """
        return len(self.processed_file_names)

    def get(self, idx: int) -> Data:
        """
        Get a processed data object.

        Args:
            idx (int): Index of the data object to retrieve.

        Returns:
            Data: The processed data object.
        """
        filepath = Path(self.processed_dir) / self.processed_file_names[idx]
        data = torch.load(filepath)
        data["tx"].x = data["tx"].x.to_dense()
        if data["tx"].x.dim() == 1:
            data["tx"].x = data["tx"].x.unsqueeze(1)
        assert data["tx"].x.dim() == 2
        # this is an issue in PyG's RandomLinkSplit, dimensions are not consistent if there is only one edge in the graph
        if hasattr(data["tx", "belongs", "bd"], "edge_label_index"):
            if data["tx", "belongs", "bd"].edge_label_index.dim() == 1:
                data["tx", "belongs", "bd"].edge_label_index = data["tx", "belongs", "bd"].edge_label_index.unsqueeze(1)
                data["tx", "belongs", "bd"].edge_label = data["tx", "belongs", "bd"].edge_label.unsqueeze(0)
            assert data["tx", "belongs", "bd"].edge_label_index.dim() == 2
        return data

```

**Comment by daniel-unyi-42** [comment]
The file is correct, but your installed version is certainly not...
Did you have the previous version installed while installing the current version?
Pls try a fresh installation and it should work!

**Comment by quail768** [comment]
@EliHei2 this was fixed but a new issue just popped up. Opening a new one.
